print('=====TCC Kuka Freska=====')
obj = input('Qual o objetivo do projeto?')
sobre = input('É uma loja de que?')
dogs = input('Quantos cachorros vão tomar banho?')
print('Com isso', dogs, 'cachorros foram tomar banho. Correto?')
fish = input('Quantos peixes tem no aquário?')
print('Vamos descobrir quantos animais tem na loja? Para isso, vamos somar a quantidade de cachorros que foram tomar banho e os peixes no aquário.')
n1 = input('Quantidade de cachorros que foram tomar banho:')
n2 = input('Quantidade de peixes no aquário:')        
soma = int(n1)+int(n2)
print('A soma de todos os animais da loja é', soma, '.')
